# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - v**
      - release-**
    branches:
      - master

jobs:
  version:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v2
        with: 
          token: ${{ secrets.DEPLOYMENT_PAT }}
      - name: Set current date as env variable
        run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Echo current date
        run: | 
          echo $MY_DATE
          echo $GITHUB_REF

      - name: Setup Git
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Bump version and tag branch
        run: |
          npm version patch -m "[skip actions] v%s"
          VERSION=$(node -p "require('./package.json').version")
        

      - name: Push change to repo
        run: |
          git push --follow-tags


  build-and-publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
