# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
      - name: Checkout new branch
        run: |
          git checkout -b "release-${GITHUB_SHA}"

      - name: Bump version and tag branch
        run: |
          npm version patch -m "v%s"
          VERSION=$(node -p "require('./package.json').version")
          git tag ${VERSION}
        
      - name: Push new branch
        run: |
          git push --set-upstream origin release-${GITHUB_SHA}

      - name: Create Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            constgh = require('@actions/github');
            const octokit =gh.getOctokit(process.env.GITHUB_TOKEN);

            const ghContext = gh.context;
            const owner = ghContext.repo.owner;
            const repo = ghContext.repo.repo;

            const title = 'Release';
            const head = ghContext.sha;
            const base = 'master';

            octokit.pulls.create({
              owner: owner,
              repo: repo,
              title: title,
              head: head,
              base: base
            });
  publish-npm:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
